### ISSUE TITLE
(PYL-C0209) Consider using f-strings

### ISSUE THREAD

**Issue by dborodin836** [dborodin836/hinkali-store#78]
## Description
f-strings are the fastest way to format strings as compared to the following methods: * using format specifiers `%`

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/dborodin836/hinkali-store/issue/PYL-C0209/occurrences/](https://deepsource.io/gh/dborodin836/hinkali-store/issue/PYL-C0209/occurrences/)

**Comment by chriswolfdesign** [comment]
I can tackle this one real quick
